name: Build Windows DirectML (分步)

on: 
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: windows-2019
    steps:
    - uses: actions/checkout@v4
    
    - name: 读取版本
      id: version
      run: |
        python -c "from backend.config import VERSION; print(f'VERSION={VERSION}')" >> $env:GITHUB_ENV
      shell: cmd
      
    - name: 设置 Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'
        
    - name: 安装基础依赖
      run: |
        echo "安装 PaddlePaddle..."
        pip install paddlepaddle==3.0.0
        echo "安装 requirements..."
        pip install -r requirements.txt
        echo "安装 DirectML..."
        pip install torch-directml
        echo "安装 QPT..."
        pip install QPT
      shell: cmd
      
    - name: 测试构建环境
      run: |
        python -c "
        import paddle
        import torch_directml
        import qpt
        print('所有依赖导入成功！')
        "
      shell: cmd
      
    - name: 执行构建
      run: |
        echo "开始构建..."
        python backend/tools/makedist.py --directml
      shell: cmd
      env:
        QPT_Action: "True"
